config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Page'
    @content = 'This is the content of About Page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
  def new

  end
  def create
    # render plain: params[:post].inspect
    @post = Post.new(postParams)
    @post.save

    redirect_to @post
  end

  private def postParams
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleblog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
<!-- Static navbar -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_path %></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><li><%= link_to "Add new", new_post_path %></li></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

<%= yield %>


</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<%= @content %>

app/views/posts/index.html.erb
<h1>All Available Blogs</h1>
<% @posts.each do |post| %>
  <h3><%= post.title  %></h3>
  <p><%= post.body %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Add new Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field(:title,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_field(:body,{:class => 'form-control'}) %>
  </p>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title  %></h1>
<h2><%= @post.body %></h2>